export const smartHrColors = {
  brand: '#00c4cc',
  primary: '#0077c7',
  danger: '#e01e5a',
  dangerForeground: '#ffffff',
  warning: '#ffcc17',
  warningForeground: '#23221e',
  success: '#4bb47d',
  successForeground: '#ffffff',
  link: '#0071c1',
  orangeAccent: '#ff9900',
  textBlack: '#23221e',
  textGrey: '#706d65',
  textDisabled: '#c1bdb7',
  stone01: '#f8f7f6',
  stone02: '#edebe8',
  stone03: '#aaa69f',
  stone04: '#4e4c49',
  white: '#ffffff',
  border: '#d6d3d0',
  overBackground: '#f2f1f0',
  actionBackground: '#d6d3d0',
  chart1: '#00c4cc',
  chart2: '#ffcd00',
  chart3: '#ff9100',
  chart4: '#e65537',
  chart5: '#2d4b9b',
  chart6: '#2d7df0',
  chart7: '#69d7ff',
  chart8: '#4bb47d',
  chart9: '#05878c',
} as const;

export const smartHrFontStack = [
  'AdjustedYuGothic',
  '"Yu Gothic"',
  'YuGothic',
  '"Hiragino Sans"',
  'sans-serif',
].join(', ');

export const smartHrTypography = {
  xxs: { fontSize: 10.67, lineHeight: 16 },
  xs: { fontSize: 12, lineHeight: 18 },
  sm: { fontSize: 13.712, lineHeight: 21 },
  base: { fontSize: 16, lineHeight: 24 },
  lg: { fontSize: 19.2, lineHeight: 29 },
  xl: { fontSize: 24, lineHeight: 30 },
  '2xl': { fontSize: 32, lineHeight: 40 },
} as const;

export const smartHrShadows = {
  xs: '0 2px 4px rgba(0, 0, 0, 0.1)',
  sm: '0 2px 4px rgba(0, 0, 0, 0.1)',
  md: '0 4px 8px rgba(0, 0, 0, 0.15)',
  lg: '0 4px 8px rgba(0, 0, 0, 0.15)',
  xl: '0 4px 8px rgba(0, 0, 0, 0.15)',
} as const;

export const smartHrHeroUITheme = {
  light: {
    colors: {
      background: smartHrColors.stone01,
      foreground: smartHrColors.textBlack,
      panel: smartHrColors.white,
      muted: smartHrColors.overBackground,
      mutedForeground: smartHrColors.textGrey,
      surface: smartHrColors.white,
      surfaceForeground: smartHrColors.textBlack,
      default: smartHrColors.stone02,
      defaultForeground: smartHrColors.stone04,
      accent: smartHrColors.primary,
      accentForeground: smartHrColors.white,
      accentSoft: smartHrColors.overBackground,
      accentSoftForeground: smartHrColors.primary,
      success: smartHrColors.success,
      successForeground: smartHrColors.successForeground,
      warning: smartHrColors.warning,
      warningForeground: smartHrColors.warningForeground,
      danger: smartHrColors.danger,
      dangerForeground: smartHrColors.dangerForeground,
      surface1: smartHrColors.white,
      surface2: smartHrColors.overBackground,
      surface3: smartHrColors.stone02,
      border: smartHrColors.border,
      divider: smartHrColors.stone03,
      link: smartHrColors.link,
      chart1: smartHrColors.chart1,
      chart2: smartHrColors.chart2,
      chart3: smartHrColors.chart3,
      chart4: smartHrColors.chart4,
      chart5: smartHrColors.chart5,
      chart6: smartHrColors.chart6,
      chart7: smartHrColors.chart7,
      chart8: smartHrColors.chart8,
      chart9: smartHrColors.chart9,
    },
    borderRadius: {
      DEFAULT: '6px',
      panel: '6px',
      'panel-inner': '4px',
    },
    opacity: {
      disabled: 0.5,
    },
  },
  dark: {
    colors: {
      background: smartHrColors.stone01,
      foreground: smartHrColors.textBlack,
      panel: smartHrColors.white,
      muted: smartHrColors.overBackground,
      mutedForeground: smartHrColors.textGrey,
      surface: smartHrColors.white,
      surfaceForeground: smartHrColors.textBlack,
      default: smartHrColors.stone02,
      defaultForeground: smartHrColors.stone04,
      accent: smartHrColors.primary,
      accentForeground: smartHrColors.white,
      accentSoft: smartHrColors.overBackground,
      accentSoftForeground: smartHrColors.primary,
      success: smartHrColors.success,
      successForeground: smartHrColors.successForeground,
      warning: smartHrColors.warning,
      warningForeground: smartHrColors.warningForeground,
      danger: smartHrColors.danger,
      dangerForeground: smartHrColors.dangerForeground,
      surface1: smartHrColors.white,
      surface2: smartHrColors.overBackground,
      surface3: smartHrColors.stone02,
      border: smartHrColors.border,
      divider: smartHrColors.stone03,
      link: smartHrColors.link,
      chart1: smartHrColors.chart1,
      chart2: smartHrColors.chart2,
      chart3: smartHrColors.chart3,
      chart4: smartHrColors.chart4,
      chart5: smartHrColors.chart5,
      chart6: smartHrColors.chart6,
      chart7: smartHrColors.chart7,
      chart8: smartHrColors.chart8,
      chart9: smartHrColors.chart9,
    },
    borderRadius: {
      DEFAULT: '6px',
      panel: '6px',
      'panel-inner': '4px',
    },
    opacity: {
      disabled: 0.5,
    },
  },
} as const;
